[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = 'FloatermNew'
on_func = 'floaterm#'
hook_add = '''
  let g:floaterm_height = 0.8
  let g:floaterm_width = 0.8
  let g:floaterm_title = ' $1/$2 '
  let g:floaterm_autoclose = 1
  nnoremap <expr> <Leader>tt floaterm#buflist#first() == -1 ? '<Cmd>FloatermNew<CR>' : '<Cmd>FloatermToggle<CR>'
'''
hook_source = '''
  autocmd vimrc User FloatermOpen nnoremap <buffer> <silent> <Leader>tt :FloatermToggle<CR>
  autocmd vimrc User FloatermOpen tnoremap <buffer> <silent> <Leader>tt <C-\><C-n>:FloatermToggle<CR>
  autocmd vimrc User FloatermOpen nnoremap <buffer> <silent> <Leader>nn :FloatermNew<CR>
  autocmd vimrc User FloatermOpen tnoremap <buffer> <silent> <Leader>nn <C-\><C-n>:FloatermNew<CR>
  autocmd vimrc User FloatermOpen nnoremap <buffer> <silent> <Leader>jj :FloatermPrev<CR>
  autocmd vimrc User FloatermOpen tnoremap <buffer> <silent> <Leader>jj <C-\><C-n>:FloatermPrev<CR>
  autocmd vimrc User FloatermOpen nnoremap <buffer> <silent> <Leader>kk :FloatermNext<CR>
  autocmd vimrc User FloatermOpen tnoremap <buffer> <silent> <Leader>kk <C-\><C-n>:FloatermNext<CR>
  autocmd vimrc QuitPre * FloatermKill!
'''
